### ISSUE TITLE
Images wont respond when clicked 

### ISSUE THREAD

**Issue by jdawsonadams** [jdawsonadams/javascript-less-carousel#1]
@mackenzierose @hannahdelaney @thomasjbradley

Markbot is saying "index.html line 7: start tag head seen but an element of the same type was already open."

As well as the "index-clicked 960px" page is too visually different from screenshot, but all my other screenshots have passed. The images aren't loading correctly when clicked. 

Does anyone know how to help :(

**Comment by HannahDelaney** [comment]
Your opening html lines are a bit jumbled, which is causing the initial trouble.

Rearrange so things are in the proper order:

```
<!DOCTYPE html>
<html lang="en-ca">
<head>
  <meta charset="utf-8">
  <title>Javascript-less Carousel</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="css/modules.css" rel="stylesheet">
  <link href="css/type.css" rel="stylesheet">
  <link href="css/main.css" rel="stylesheet">
</head>



```

Do the images display at any of the sizes?
